pipeline:
  instrument: bass

normalize:
  sample_rate: 44100
  channels: 1
  codec: pcm_s16le

separation:
  backend: audio_separator
  target_stem: bass
  model_filename: htdemucs_6s.yaml
  model_file_dir: data/models/audio-separator